PROMPT_IHL_LEGAL_FRAMEWORK = """
### International law applicable to situations of armed conflict

Situations of armed conflicts, or aspects thereof, are governed by various branches of public international law.

Public international, also known as the law of nations, consists of rules and principles governing the relations between states. Situations of armed conflicts, or aspects thereof, are governed by various branches of public international law. Public international law regulates the use of force between states in international relations. The United Nations Charter generally prohibits the use of force in international relations. Nevertheless, the question of the legality of the use of force has no bearing upon the application of international humanitarian law  also known as the law of war or the law of armed conflict. Regardless of the legality of the use of force, international humanitarian law must be applied equally by all belligerents in an armed conflict. International humanitarian law provides for the protection of those who are not, or no longer, participating in fighting, and restricts the means and methods of warfare. International humanitarian law only applies during times of armed conflict. In contrast, international human rights law applies at all times, i.e. both in peace time and in situations of armed conflicts. Although different in scope than international humanitarian law, international human rights law provides complementary protection to those affected by armed conflicts. Serious violations and abuses of international humanitarian law and human rights law are common in many armed conflicts. In some circumstances, such violations constitute international crimes under international criminal law. International criminal law provides for individual criminal responsibility for the crime of genocide, crimes against humanity, war crimes, and the crime of aggression.

The RULAC focuses on the use of force, international humanitarian law, international human rights law, and international criminal law because these bodies of public international law are particularly relevant for the protection of those affected by armed conflict. This does not mean that other branches of international law do not play a role, such as refugee law, environmental law, and weapons law. Similarly, domestic law continues to apply during times of armed conflict and plays a crucial role in the implementation of international law. However, the lawfulness of an act under domestic law does neither determine the lawfulness of an act under international law nor can domestic law be invoked to justify a violation of international law.

#### Use of force

The body of international law that governs the use of force between states is called jus ad bellum. Jus ad bellum determines when one state may lawfully use force against another. It is sometimes called jus contra bellum to reflect that it is a legal regime based on the general prohibition of the use of force between states.

Under customary international law and the Charter of the United Nations , the use of force is prohibited with two generally accepted exceptions. First, the United Nations Security Council may authorize the use force to maintain and restore peace and security. Under the collective security system set up by Chapter VII of the Charter of the United Nations, the Security Council is to take measures in case of a threat to the peace, breach of the peace or act of aggression. Such measures include the authorization of military action. Second, states may use force when acting in self-defence against an armed attack. Not every use of force amounts to an armed attack. An armed action must present a certain degree of gravity to entail the right to self-defence. The right to self-defence may be exercised individually or collectively. For self-defence to be lawful, the use of force in response to an armed attack must be both necessary and proportionate. It remains controversial whether the right to self-defence encompasses the right to self-defence against an armed attack by a non-state actor or a right to pre-emptive self-defence. Similarly, other purported exceptions such as humanitarian intervention or the use of force under the responsibility to protect doctrine are contested.

#### Jus ad bellum and international humanitarian law

International humanitarian law operates independently from questions surrounding the legality of the use of force between states. Regardless of the legality of the use force or more generally the reasons given for resorting to force, the obligations under international humanitarian law remain the same for all parties to a conflict. In other words, the application of humanitarian law does not involve a judgment on the legality or legitimacy of the resort to force. For example, a state claiming to act in self-defence against foreign aggression has exactly the same obligations under international humanitarian law as the purported aggressor. Any other approach would led to controversy and undermine international humanitarian law as each party would argue to be the victim of aggression.

Similarly, international humanitarian law does not involve a judgment on the legality or legitimacy of use of force by armed groups. Taking up arms against the state is not a violation of international humanitarian law. In contrast, domestic law usually prohibits taking up arms against the state. Therefore, members of armed groups may face prosecution and punishment under domestic law for taking up arms, including for acts that are lawful under international humanitarian law.

#### Interventions short of the use of force

Coercive acts that do not amount to a use of force are prohibited under the principle of non-intervention. Direct or indirect support of a foreign state to an armed group opposing the territorial government in the form of funds, weapons, or training constitutes a breach of the principle of non-intervention.

### International humanitarian law

International humanitarian law, also called the law of armed conflict or the law(s) of war, is the branch of international law that regulates conduct in an armed conflict.

International humanitarian law strives to limit the effects of armed conflicts. On the one hand, it provides for the protection of those who are not or no longer participating in hostilities, such as civilians, the wounded, sick and shipwrecked, or captured combatants. On the other hand, international humanitarian law limits the means and methods of warfare, or, in other words, the weapons and tactics that may be used. In particular, it prohibits means and methods of warfare that do not discriminate between those who are not or no longer participating in hostilities and those who do. Those who are participating in hostilities are protected by the prohibition of using means or methods of warfare that are of a nature to cause superfluous injury or unnecessary suffering.

International humanitarian law binds all parties to an armed conflict, including non-state armed groups. Pursuant to the principle of equality of belligerents, international humanitarian law applies equally to all parties to an armed conflict: Every party to an armed conflict has the same rights and obligations under international humanitarian law, not more or less obligations depending on whether or not their resort to force is lawful or not. In other words, international humanitarian law applies independently from any considerations concerning the lawfulness to use force. This separation between the application of international humanitarian law and the legal regime governing the use of force is necessary for both humanitarian and practical reasons. On the one hand, at least the parties to a conflict will always disagree on who resorted to force unlawfully or whose cause is just. On the other hand, those affected by the conflict are in need of the same protection.
 
#### Sources: Where to find international humanitarian law?

The core of international humanitarian law rules can be found in the four 1949 Geneva Conventions and their two 1977 Additional Protocols. The four 1949 Geneva Conventions seek to protect those who do not, or no longer actively participate in hostilities, namely wounded and sick members of armed forces in land warfare, sick, wounded and shipwrecked members of armed forces at sea, prisoners of war, and civilians. Protected persons shall in all circumstances be treated humanely and cared for. The Geneva Conventions are universally ratified. The 1977 Additional Protocol I to the 1949 Geneva Conventions relating to the protection of victims in international armed conflicts and the 1977 Additional Protocol II to the 1949 Geneva Conventions relating to the protection of victims in non-international armed conflicts further develop the protection of those not or no longer participating in hostilities. In addition, the two 1977 Additional Protocols provide for rules on means and methods of warfare. Finally, there are several treaties dedicated to specific topics. A series of such treaties prohibit or restrict the use of certain weapons, such as biological weapons, chemical weapons, incendiary weapons, blinding laser weapons, anti-personnel mines, and cluster munitions. Other treaties provide for the specific protection of cultural property  or the environment.

Customary international law complements the protection provided by treaty law. Customary international humanitarian law applies universally and binds all parties to a conflict, independently from the application of treaty law. In particular, customary international humanitarian law governing non-international armed conflicts is more detailed than treaty law governing non-international armed conflicts. The ICRC maintains a searchable database that identifies the rules of customary international humanitarian law.

#### When does international humanitarian law apply?

International humanitarian law applies only to armed conflicts. It does not cover other situations of violence, such as riots or other internal  tensions or disturbances. International humanitarian law distinguishes between international armed conflicts and armed conflicts of non-international character. A wide array of provisions, including those in the four 1949 Geneva Conventions and the 1977 Additional Protocol I, govern international armed conflicts, i.e. conflicts between at least two States. Non-international armed conflicts are subject to a more limited set of rules provided for in common Article 3 to the four 1949 Geneva Conventions. and in the 1977 Additional Protocol II. The two regimes are converging under customary international law, in particular in relation to the conduct of hostilities. Yet, important differences remain, in particular for the status of persons. During international armed conflicts, combatants have so-called combatant immunity: they are immune from prosecutions for belligerent acts that comply with international humanitarian law, and they are entitled to prisoner of war status when captured. In contrast, fighters during a non-international armed conflict, although still entitled to legal protection, may be prosecuted for mere participation in hostilities under domestic law, including for acts that comply with international humanitarian law.

#### What are the basic principles of international humanitarian law?

International humanitarian law strives to limit the effects of armed conflict and minimize human suffering. International humanitarian law rests on a careful balancing between the foundational principles of humanity and military necessity. The principle of military necessity can be both limiting and permissive. As a limiting principle, military necessity restrains the lawful use of force to what is necessary to achieve a military goal and prohibits violence excessive to achieve this aim. The principle of military necessity operates as permissive principle that allows death and destruction when necessary from a military point of view. Yet, the principle of military necessity cannot be invoked to justify violations of international humanitarian law.

Military necessity is counter-balanced by the principle of humanity. The principle of humanity protects those who are not or no longer actively participating in hostilities and provides for their humane treatment at all times. Furthermore, the principle of humanity protects those who directly participate in hostilities from superfluous injury or unnecessary suffering.

From these two foundational principles flow a series of other basic principles upon which international humanitarian law rests. The principle of distinction requires parties to an armed conflict to distinguish between combatants and civilians and between military and civilian objects. Attacks against lawful military objectives are prohibited if the attack 'may be expected' to result in excessive civilian harm under the principle of proportionality."""

PROMPT_IHR_LEGAL_FRAMEWORK = """
### International human rights law

International human rights law is the body of international law that seeks the protection of rights that are inherent to the human person.

Human rights are the basic rights and freedoms that human beings are entitled to. International human rights law seeks to guarantee human rights to all human beings without discrimination. Under international human rights law, states are not only to refrain from interfering with the exercise and enjoyment of human rights, so-called negative obligations, but also to take steps to promote, protect and fulfil their enjoyment, so-called positive obligations. Positive obligations require States to take steps to ensure that non-state actors do not impede the enjoyment of human rights. While international humanitarian law applies to both state and non-state actors, it remains contested whether and under what circumstances, non-state actors have human rights obligations. Human rights law applies at all times, including during times of armed conflict. States may derogate from their human rights treaty obligations during a state of emergency, including during times of armed conflict.

International human rights treaties usually provide for a monitoring system to scrutinise compliance and assist states parties in the implementation of their obligations. To a varying degree, treaties create procedures where individuals can bring complaints against states for alleged human rights violations. Victims of human rights violations during times of armed conflict may use these procedures to the extent that they are available. International humanitarian law does not have a similar complaints mechanism.

#### Sources: Where to find international human rights law?

Modern international human rights law developed in the wake of the Second World War with the adoption of the 1948 Universal Declaration of Human Rights. Since then, the bulk of the international legal framework of human rights protection has emerged through treaties on specific rights or sets of rights intended to augment the Universal Declaration and make the rights contained therein legally binding and subject to monitoring and accountability mechanisms. Most notably, the United Nations General Assembly adopted in 1966 the International Covenant on Civil and Political Rights and the International Covenant on Economic, Social, and Cultural Rights. Taken together with the Universal Declaration, these three documents are often referred to as the International Bill of Rights. Other specialised treaties on human rights treaties adopted at  the universal level are:

    - the 1965 International Convention on the Elimination of All Forms of Racial Discrimination
    - the 1984 Convention against Torture and Other Cruel, Inhuman, or Degrading Treatment or Punishment
    - the 1979 Convention on the Elimination of All Forms of Discrimination against Women
    - the 1989 Convention on the Rights of the Child and its 2000 Optional Protocol on the Involvement of Children in Armed Conflict
    - the 1990 International Convention on the Protection of the Rights of All Migrant Workers and Members of Their Families
    - the 2006 International Convention for the Protection of All Persons from Enforced Disappearance
    - the 2006 Convention on the Rights of Persons with Disabilities

In parallel, human rights treaties were adopted at the regional level, in particular the 1950 European Convention on Human Rights, the 1969 American Convention on Human Rights,  the 1981 African Charter on Human and Peoples' Rights, and the 2004 Arab Charter on Human Rights.

In addition to treaty law, there exists a significant body of customary international human rights law. The question whether or not a human right has become an obligation under customary international law is  a complex one. However, the customary nature of the Universal Declaration of Human Rights is frequently accepted. Moreover, some norms like the prohibition of torture or apartheid amount to jus cogens norms, i.e. a norm that is 'accepted and recognized by the international community as a whole as a norm from which no derogation is permitted.'

#### What are derogations?

International human rights law continues to apply in times of armed conflicts. Yet some human rights treaties envisage a system of derogations. Derogations allow states parties to adjust some of their obligations under the treaty in exceptional situations.

The existence of a situation amounting to a public emergency is a fundamental requirement for triggering the derogation clause. Non-international armed conflicts or acts of terrorism are frequently asserted as justifying the declaration of a state of emergency. Yet, an armed conflict does not automatically qualify as a state of emergency as it depends on the context. For a state of emergency to exist, there must be an actual and imminent threat to the organized life of the community. The meaning of state of emergency in the sense of international human rights treaties does not necessarily correspond to the definition of state of emergency within domestic law. States must officially proclaim a state of emergency, and notify the relevant international supervision body of the proclamation, the reasons for derogation and the measures taken.

International human rights treaties provide for a series of substantive limits to derogations. First, derogation measures must be 'strictly required by the exigencies of the situation.' Hence, states must limit the severity, duration and geographic scope of derogation measures to the extent strictly required. In other words, derogation measures must be limited to what is really needed to address the situation of crisis. Consequently, entire rights cannot be eliminated or suspended during a state of emergency. States must put in place the necessary safeguards to prevent abuse. Second, derogation measures should be consistent with other obligations of the derogating state under international law, including international humanitarian law and international refugee law. Third, derogation measures must not involve discrimination solely on the ground of race, colour, sex, language, religion or social origin. Finally States cannot derogate from certain rights. All derogation clauses provide for a list of such rights. The list varies, yet common to all treaties are the right to life, the prohibition of slavery, the prohibition of torture and cruel, inhuman or degrading treatment or punishment, and prohibition of retroactive penal measures. Other rights that are not expressly listed are also considered non-derogable, in particular rights, or aspects thereof, that reflect other obligations under international law, such as the principle of humane treatment of all persons deprived of liberty.

#### Do human rights treaties apply abroad?

Most human rights treaties, albeit with slightly different wordings, specify that they apply where the state concerned exercises jurisdiction. Jurisdiction always includes a state's territory.

Armed conflicts often involve operations outside a state's territorial boundaries, which raises the question whether individuals fall within the jurisdiction of the state in such circumstances. From international jurisprudence, two models to establish the extraterritorial application of human rights treaties emerge. First, under the so-called spatial or territorial mode, jurisdiction for the purpose of human rights treaties exists when a state exercises effective control over an area, including as a consequence of military action, whether lawful or not. This includes cases of military occupation. Second, under the personal model, jurisdiction for the purpose of human rights treaties exist when state agents operating outside state territory exercise authority and control over individuals, such as for example when arresting individual.""" 

PROMPT_ICL_LEGAL_FRAMEWORK = """
### International criminal law

International criminal law is the body of public international law that establishes individual criminal responsibility for international crimes, such as war crimes, crimes against humanity, genocide, and aggression.

The exact definition of an international crime remains debated, but it is normally understand as an act that violates fundamental interests of the international community and entails individual criminal responsibility. The generally accepted core international crimes are war crimes, crimes against humanity, genocide, and aggression. Depending on the concept of international crimes used, other criminalized conduct such as piracy or torture may also be considered an international crime.

Many violations of international humanitarian law are nowadays considered war crimes. Criminal prosecutions for war crimes are a means to implement international humanitarian law . However, international humanitarian law is broader than the concept of war crimes: not every violation of international humanitarian law constitutes a war crime.

The current system of international criminal law works through international ad hoc tribunals, mixed or hybrid tribunals, and the International Criminal Court, as well as national courts. One of the legal consequences of framing an act as an international crime is that it may give rise to what is called universal jurisdiction: pursuant to the principle of universal jurisdiction, any state is allowed to try alleged perpetrators of international crimes, even in the absence of any link between the accused and the state exercising jurisdiction.

#### Sources: Where to find international criminal law?

The genesis of international criminal law as a branch of international law can be traced back to the London Charter of the International Military Tribunal adopted in 1945. Since then, and especially over the past two decades with the proliferation of various ad hoc tribunals and the establishment of International Criminal Court, international criminal law has developed considerably.

Statutes of international tribunals are the main treaties that are used by international criminal courts as a legal basis and guidelines for their activities, most importantly the Statute of the International Criminal Court. Other treaties include international instruments directly criminalizing certain types of conduct, such as the Convention on the Prevention and Punishment of the Crime of Genocide, and conventions which may be taken into account for the identification of customary criminal rules. The 1949 Geneva Conventions with their Additional Protocols may serve both purposes.

Customary international law may fill in the gaps, where treaties do not contain explicit criminal norms. Such norms can be inferred from the jurisprudence of both international and domestic tribunals.

#### What are war crimes?

War crimes are serious violations of international humanitarian law that entail individual criminal responsibility. War crimes can only be committed during times of armed conflict, either international or non-international, as understood under international humanitarian law. While it is necessary that the crime in question was committed during an armed conflict, this is in itself not sufficient: the crime must be sufficiently linked to the armed conflict. This so-called nexus requirement is satisfied if the armed conflict played a substantial role in the perpetrator's decision to commit the crime, his or her ability to commit it, or the manner in which the crime was committed.  

In order to define an act as a war crime, this act must, besides having nexus to an armed conflict, be a serious violation of international humanitarian law and entail individual criminal responsibility. During international armed conflicts, the Geneva Convention of 1949 and the Additional Protocol I thereto of 1977 criminalize a certain number of acts as 'grave breaches', and oblige state parties to prosecute individuals responsible for such acts. Thus, the grave breaches automatically qualify for both criteria of seriousness and criminalization. Acts that are not defined as grave breaches must be examined on a case by case basis. As for the seriousness criterion, according to the Tadić decision by the International Criminal Tribunal for the Former Yugoslavia, a violation is serious enough if it constitutes a breach of a rule protecting important values and involves grave consequences for the victim. The second criterion is the criminalization of the act. According to the same decision and further jurisprudence, the violation of the rule must entail the individual criminal responsibility under customary or conventional law.

#### What is the International Criminal Court?

The International Criminal Court is a permanent international court established by the 1998 Rome Statute to investigate, prosecute, and try alleged perpetrators of war crimes, crimes against humanity, genocide, and the crime of aggression. To date, more than 120 countries have ratified the Statute. In addition to setting out the crimes that fall within the jurisdiction of the Court, the Statute provides for the conditions under which the Court may exercise jurisdiction. It may exercise jurisdiction over crimes committed by nationals of state parties or in the territory of these state parties since the date of entry into force of the Rome Statute for the state party in question.

In addition, the United Nations Security Council can refer a situation to the International Criminal Court, triggering its jurisdiction and extending it to countries that may not be parties to the 1998 Rome Statute.""" 